# 发布Python包到PyPI的工作流
# 当创建发布版本时自动运行
# 参考: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

# 此工作流使用的第三方操作受其各自的服务条款、隐私政策和支持文档约束

name: 发布Python包到PyPI
on:
  # 在创建发布版本时触发
  release:
    types: [published]
  # 允许手动触发
  workflow_dispatch:

jobs:
  # 构建和发布作业
  deploy:
    runs-on: ubuntu-latest
    # 添加权限设置
    permissions:
      contents: read
      # 允许发布到PyPI
      id-token: write
    steps:
      # 检出代码仓库
      - uses: actions/checkout@v4
      
      # 设置Python环境
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # 启用依赖缓存以加速构建
          cache: "pip"
      
      # 安装构建依赖
      - name: 安装构建依赖
        run: |
          python -m pip install --upgrade pip
          pip install build
      
      # 构建包
      - name: 构建包
        run: python -m build
      
      # 使用受信任发布向PyPI发布包
      # 参考: https://docs.pypi.org/trusted-publishers/
      - name: 发布包到PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
